# 现有的配置
title: Yu Xinda
state: Master student
email: yuxindaaaaa@gmail.com
university: Huzhou University
avatar: ./assets/img/avatar.png # 确保路径正确

# --- 新增以下字段以启用带图标的链接 ---
location: Zhejiang, China  # 如果需要显示地点
github_username: yourusername  # 仅填写用户名
google_scholar: https://scholar.google.com/citations?user=XXXX  # 完整链接
researchgate: https://www.researchgate.net/profile/Your-Name # 完整链接
orcid: https://orcid.org/0000-xxxx-xxxx-xxxx # 完整链接
wechat_qrcode: "https://github.com/Yu-Xinda/Yu-Xinda.github.io/blob/main/_news/image/academics-activity.png"
# 自动深夜模式
auto_dark_mode: true

# 字体样式
font: "Serif" # or "Sans Serif"

#模板的默认配置，若不更换模板可忽视
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# 以下的文件开头会被显示成网页，不然以下划线为开头的文件会被Jekyll自动隐藏
include:
  - _about
  - _news
  - _publication
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
